### ISSUE TITLE
Support and Game Engine Suggestions

### ISSUE THREAD

**Issue by sprtkd** [carlosedp/PSP-StacklessPython#1]
Fabulous work.
Sure PSP is outdated. But need for homebrews is there.

If you could suggest on any game engine library I could use.
Cheers.

**Comment by carlosedp** [comment]
It's been a while since this is updated. I believe you could use PyGame but I'm not sure since I don't have a PSP anymore.

Maybe it could be tested with a PSP emulator (https://www.ppsspp.org/) but I'm a little busy with other projects to test it right now.
