### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by brostosjoined** [carlosedp/PSP-StacklessPython#3]
Can this be updated to the latest stackless python @carlosedp

**Comment by carlosedp** [comment]
Hi, unfortunately I can't... I don't have a PSP anymore and this repo is here for historical reasons or if someone would like to take it's duties.

**Comment by brostosjoined** [comment]
You can use the [ppsspp](https://github.com/hrydgard/ppsspp) emulator both on pc and mobile if you have time meanwhile let me give it some try. First time though.

**Comment by brostosjoined** [comment]
I tried my best. I you ever find the intrest ping ill help with testing
